- type: accessLevel
  id: HeadOfSecurity
  name: id-card-access-level-head-of-security

- type: accessLevel
  id: Security
  name: id-card-access-level-security

- type: accessLevel
  id: Armory
  name: id-card-access-level-armory

- type: accessLevel
  id: Brig
  name: id-card-access-level-brig

- type: accessLevel
  id: Detective
  name: id-card-access-level-detective

- type: accessLevel
  id: Instructor
  name: id-card-access-level-instructor

- type: accessGroup
  id: Security
  tags:
  - HeadOfSecurity
  - Security
  - Armory
  - Brig
  - Detective
  - Instructor

- type: accessGroup
  id: Armory
  tags:
  - Security
  - Armory
  - Brig
