- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 19200 # Ganimed-RoleTime (320m)
  startingGear: PsychologistGear
  icon: "Psychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry

- type: startingGear
  id: PsychologistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPsychologist
    back: ClothingBackpackPsychologistFilled
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
  innerclothingskirt: ClothingUniformJumpskirtPsychologist # Corvax-Resprite
  satchel: ClothingBackpackSatchelPsychologistFilled
  duffelbag: ClothingBackpackDuffelPsychologistFilled
