- type: job
  id: IAA
  name: job-name-iaa
  playTimeTracker: JobIAA
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 86400 # Ganimed-RoleTime
  startingGear: IAAGear
  icon: "IAA"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Service
    - Brig
    - Maintenance
    - Command
    - External

- type: startingGear
  id: IAAGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackIAAFilled
    shoes: ClothingShoesColorBlack
    id: IAAPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetIAA
    neck: ClothingNeckLawyerbadge
  innerclothingskirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelIAAFilled
  duffelbag: ClothingBackpackDuffelIAAFilled
